# Generated by Django 2.2.4 on 2019-08-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='posit',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='bar',
            name='url',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
