# Generated by Django 2.2.4 on 2019-08-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpick', '0002_auto_20190809_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cock',
        ),
    ]
